# Generated by Django 6.0.2 on 2026-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('sex', models.IntegerField()),
                ('level', models.TextField()),
                ('reputation', models.IntegerField()),
                ('role', models.TextField()),
                ('birth_date', models.DateField()),
                ('registration_date', models.DateField()),
                ('image', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
